// Mocks generated by Mockito 5.4.0 from annotations
// in todo_app/test/data/network/rest_api/app_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/data/network/rest_api/app_api.dart' as _i3;
import 'package:todo_app/data/response/responses.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationResponse_0 extends _i1.SmartFake
    implements _i2.AuthenticationResponse {
  _FakeAuthenticationResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppServiceClient extends _i1.Mock implements _i3.AppServiceClient {
  MockAppServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthenticationResponse> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthenticationResponse>.value(
            _FakeAuthenticationResponse_0(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationResponse>);
}
